In [76]:
import numpy as np
import pandas as pd

In [77]:
df=pd.read_csv('data.csv')
df.columns
df

voiceID  localJitter  localabsoluteJitter  rapJitter  ppq5Jitter   
0    5388081     0.006589             0.000040   0.003796    0.003223  \
1    5388083     0.005943             0.000046   0.003444    0.002929   
2    5388084     0.003878             0.000034   0.001850    0.001864   
3    5388094     0.002998             0.000033   0.001331    0.001720   
4    5388096     0.009033             0.000067   0.005031    0.004842   
..       ...          ...                  ...        ...         ...   
836  5398003     0.008805             0.000079   0.005414    0.004470   
837  5398012     0.004507             0.000037   0.002488    0.002680   
838  5398013     0.005298             0.000044   0.002674    0.002673   
839  5398016     0.005173             0.000058   0.002541    0.003012   
840  5398026     0.003144             0.000015   0.001784    0.001843   

     ddpJitter  localShimmer  localdbShimmer  apq3Shimmer  aqpq5Shimmer  ...   
0     0.011387      0.054058        0.517247     0.032026      0.030353  ...  \
1     0.010333      0.043381        0.390473     0.023001      0.024648  ...   
2     0.005550      0.044087        0.396595     0.023004      0.029224  ...   
3     0.003994      0.036390        0.321520     0.015786      0.020569  ...   
4     0.015093      0.072445        0.653206     0.038597      0.042474  ...   
..         ...           ...             ...          ...           ...  ...   
836   0.016241      0.033671        0.296418     0.017675      0.019538  ...   
837   0.007464      0.070381        0.612945     0.037591      0.042544  ...   
838   0.008023      0.030512        0.279126     0.015527      0.017023  ...   
839   0.007622      0.053419        0.469627     0.022244      0.028764  ...   
840   0.005353      0.018290        0.158278     0.009841      0.011492  ...   

     min_pitch  max_pitch  n_pulses  n_periods  mean_period   
0       80.873    175.207      1569       1568     0.006033  \
1      124.836    225.544      1215       1212     0.007771   
2       98.092    210.615      1042       1031     0.008837   
3       88.533    104.424       860        859     0.010861   
4       67.738    186.335      1268       1265     0.007421   
..         ...        ...       ...        ...          ...   
836    103.308    115.324      1050       1049     0.008923   
837    116.849    125.492      1224       1223     0.008197   
838    115.922    172.658      1149       1145     0.008331   
839     86.085     99.825       898        897     0.011171   
840    207.235    226.628      2143       2142     0.004680   

     standard_deviation_period  fraction_unvoiced_frames  num_voice_breaks   
0                     0.000317                   0.05711                 0  \
1                     0.000219                   0.05210                 2   
2                     0.000564                   0.04409                 8   
3                     0.000165                   0.06413                 0   
4                     0.001718                   0.06513                 2   
..                         ...                       ...               ...   
836                   0.000118                   0.06313                 0   
837                   0.000074                   0.00000                 0   
838                   0.000236                   0.04309                 3   
839                   0.000252                   0.00000                 0   
840                   0.000045                   0.00000                 0   

     degree_voice_breaks  class  
0                0.00000      1  
1                0.02362      0  
2                0.08753      0  
3                0.00000      0  
4                0.01617      0  
..                   ...    ...  
836              0.00000      0  
837              0.00000      0  
838              0.02780      0  
839              0.00000      0  
840              0.00000      1  

[841 rows x 28 columns]

In [78]:
#dropping the columns with names 'class' and 'voiceID'
X=df.loc[:, df.columns !='class']
X=X.loc[:, X.columns !='voiceID']
X

localJitter  localabsoluteJitter  rapJitter  ppq5Jitter  ddpJitter   
0       0.006589             0.000040   0.003796    0.003223   0.011387  \
1       0.005943             0.000046   0.003444    0.002929   0.010333   
2       0.003878             0.000034   0.001850    0.001864   0.005550   
3       0.002998             0.000033   0.001331    0.001720   0.003994   
4       0.009033             0.000067   0.005031    0.004842   0.015093   
..           ...                  ...        ...         ...        ...   
836     0.008805             0.000079   0.005414    0.004470   0.016241   
837     0.004507             0.000037   0.002488    0.002680   0.007464   
838     0.005298             0.000044   0.002674    0.002673   0.008023   
839     0.005173             0.000058   0.002541    0.003012   0.007622   
840     0.003144             0.000015   0.001784    0.001843   0.005353   

     localShimmer  localdbShimmer  apq3Shimmer  aqpq5Shimmer  apq11Shimmer   
0        0.054058        0.517247     0.032026      0.030353      0.034403  \
1        0.043381        0.390473     0.023001      0.024648      0.033738   
2        0.044087        0.396595     0.023004      0.029224      0.036338   
3        0.036390        0.321520     0.015786      0.020569      0.032581   
4        0.072445        0.653206     0.038597      0.042474      0.052674   
..            ...             ...          ...           ...           ...   
836      0.033671        0.296418     0.017675      0.019538      0.028270   
837      0.070381        0.612945     0.037591      0.042544      0.054537   
838      0.030512        0.279126     0.015527      0.017023      0.024713   
839      0.053419        0.469627     0.022244      0.028764      0.055433   
840      0.018290        0.158278     0.009841      0.011492      0.014976   

     ...    stdevF0  min_pitch  max_pitch  n_pulses  n_periods  mean_period   
0    ...   5.184025     80.873    175.207      1569       1568     0.006033  \
1    ...   4.619268    124.836    225.544      1215       1212     0.007771   
2    ...   9.408769     98.092    210.615      1042       1031     0.008837   
3    ...   1.410114     88.533    104.424       860        859     0.010861   
4    ...  24.619639     67.738    186.335      1268       1265     0.007421   
..   ...        ...        ...        ...       ...        ...          ...   
836  ...   1.282543    103.308    115.324      1050       1049     0.008923   
837  ...   1.041811    116.849    125.492      1224       1223     0.008197   
838  ...   3.579614    115.922    172.658      1149       1145     0.008331   
839  ...   2.039086     86.085     99.825       898        897     0.011171   
840  ...   1.953537    207.235    226.628      2143       2142     0.004680   

     standard_deviation_period  fraction_unvoiced_frames  num_voice_breaks   
0                     0.000317                   0.05711                 0  \
1                     0.000219                   0.05210                 2   
2                     0.000564                   0.04409                 8   
3                     0.000165                   0.06413                 0   
4                     0.001718                   0.06513                 2   
..                         ...                       ...               ...   
836                   0.000118                   0.06313                 0   
837                   0.000074                   0.00000                 0   
838                   0.000236                   0.04309                 3   
839                   0.000252                   0.00000                 0   
840                   0.000045                   0.00000                 0   

     degree_voice_breaks  
0                0.00000  
1                0.02362  
2                0.08753  
3                0.00000  
4                0.01617  
..                   ...  
836              0.00000  
837              0.00000  
838              0.02780  
839        

In [79]:
from collections import Counter
Y=df['class']
Counter(Y)

Counter({0: 735, 1: 106})

In [80]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(X)
X_norm = pd.DataFrame(x_scaled)


In [81]:
X.columns

Index(['localJitter', 'localabsoluteJitter', 'rapJitter', 'ppq5Jitter',
       'ddpJitter', 'localShimmer', 'localdbShimmer', 'apq3Shimmer',
       'aqpq5Shimmer', 'apq11Shimmer', 'ddaShimmer', 'ac', 'nth', 'htn',
       'median_pitch', 'meanF0', 'stdevF0', 'min_pitch', 'max_pitch',
       'n_pulses', 'n_periods', 'mean_period', 'standard_deviation_period',
       'fraction_unvoiced_frames', 'num_voice_breaks', 'degree_voice_breaks'],
      dtype='object')

In [82]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [83]:
X_norm

0         1         2         3         4         5         6    
0    0.073799  0.062739  0.076446  0.054296  0.076446  0.174736  0.200454  \
1    0.065183  0.074394  0.068356  0.048331  0.068356  0.132789  0.141640   
2    0.037658  0.053057  0.031635  0.026760  0.031635  0.135561  0.144480   
3    0.025915  0.050009  0.019694  0.023846  0.019694  0.105321  0.109650   
4    0.106393  0.111690  0.104897  0.087099  0.104897  0.246971  0.263531   
..        ...       ...       ...       ...       ...       ...       ...   
836  0.103349  0.132490  0.113714  0.079546  0.113714  0.094639  0.098004   
837  0.046038  0.057719  0.046333  0.043298  0.046333  0.238862  0.244852   
838  0.056583  0.070629  0.050622  0.043157  0.050622  0.082229  0.089982   
839  0.054917  0.095194  0.047544  0.050025  0.047544  0.172224  0.178362   
840  0.027866  0.017913  0.030120  0.026332  0.030120  0.034211  0.033916   

           7         8         9   ...        16        17        18   
0    0.254290  0.147508  0.081204  ...  0.043402  0.063931  0.227452  \
1    0.173810  0.115216  0.079227  ...  0.037993  0.201828  0.347314   
2    0.173837  0.141115  0.086955  ...  0.083862  0.117941  0.311765   
3    0.109470  0.092126  0.075787  ...  0.007260  0.087958  0.058904   
4    0.312887  0.216111  0.135520  ...  0.229535  0.022731  0.253950   
..        ...       ...       ...  ...       ...       ...       ...   
836  0.126311  0.086294  0.062973  ...  0.006038  0.134302  0.084859   
837  0.303916  0.216505  0.141059  ...  0.003733  0.176776  0.109071   
838  0.107163  0.072059  0.052398  ...  0.028037  0.173868  0.221382   
839  0.167064  0.138515  0.143721  ...  0.013283  0.080280  0.047953   
840  0.056453  0.040753  0.023454  ...  0.012464  0.460285  0.349895   

           19        20        21        22        23        24        25  
0    0.405246  0.406200  0.330390  0.072614  0.061817  0.000000  0.000000  
1    0.310493  0.311064  0.490113  0.048702  0.056394  0.048780  0.024732  
2    0.264186  0.262694  0.588009  0.132904  0.047724  0.195122  0.091652  
3    0.215471  0.216729  0.774077  0.035519  0.069416  0.000000  0.000000  
4    0.324679  0.325227  0.457963  0.414830  0.070498  0.048780  0.016931  
..        ...       ...       ...       ...       ...       ...       ...  
836  0.266328  0.267504  0.595977  0.023943  0.068334  0.000000  0.000000  
837  0.312901  0.314003  0.529250  0.013263  0.000000  0.000000  0.000000  
838  0.292827  0.293159  0.541509  0.052828  0.046642  0.073171  0.029109  
839  0.225642  0.226884  0.802515  0.056706  0.000000  0.000000  0.000000  
840  0.558887  0.559594  0.206056  0.006057  0.000000  0.000000  0.000000  

[841 rows x 26 columns]

In [104]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=50, random_state=5,class_weight={0:2.3,1:1})
classifier.fit(X_train, y_train)

RandomForestClassifier(class_weight={0: 2.3, 1: 1}, n_estimators=50,
                       random_state=5)

In [110]:
y_pred = classifier.predict(X_train)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
print(confusion_matrix(y_train,y_pred))
print(classification_report(y_train,y_pred))
print(accuracy_score(y_train, y_pred))
print(f1_score(y_train, y_pred))

[[584   0]
 [  1  87]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       584
           1       1.00      0.99      0.99        88

    accuracy                           1.00       672
   macro avg       1.00      0.99      1.00       672
weighted avg       1.00      1.00      1.00       672

0.9985119047619048
0.9942857142857142


In [106]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred))

[[151   0]
 [ 16   2]]
              precision    recall  f1-score   support

           0       0.90      1.00      0.95       151
           1       1.00      0.11      0.20        18

    accuracy                           0.91       169
   macro avg       0.95      0.56      0.57       169
weighted avg       0.91      0.91      0.87       169

0.9053254437869822
0.19999999999999998


In [107]:
from xgboost import XGBClassifier

model = XGBClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_train)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
print(confusion_matrix(y_train,y_pred))
print(classification_report(y_train,y_pred))
print(accuracy_score(y_train, y_pred))
print(f1_score(y_train, y_pred))

[[584   0]
 [  0  88]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       584
           1       1.00      1.00      1.00        88

    accuracy                           1.00       672
   macro avg       1.00      1.00      1.00       672
weighted avg       1.00      1.00      1.00       672

1.0
1.0


In [108]:
y_pred = model.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred))

[[145   6]
 [ 15   3]]
              precision    recall  f1-score   support

           0       0.91      0.96      0.93       151
           1       0.33      0.17      0.22        18

    accuracy                           0.88       169
   macro avg       0.62      0.56      0.58       169
weighted avg       0.85      0.88      0.86       169

0.8757396449704142
0.2222222222222222


In [16]:
import joblib
joblib.dump(classifier, "./rf.joblib")

['./rf.joblib']